### ISSUE TITLE
Seeking clarification

### ISSUE THREAD

**Issue by rhiever** [greenelab/gcb535challenge#1]
I see that there's four data sets currently in the repo. Are we meant to create a model for each data set, and then a separate validation set will be provided later? Or are we meant to train on `D*_S1` and test on `D*_S2`, and another validation set will be provided later?

**Comment by cgreene** [comment]
Hi @rhiever,

You can do whatever you like with the datasets in the data/ directory. We'll also provide you with one more set that contains labels when we provide it to the students (S3). We'll provide a final set (D4) with stripped labels at that time as well. We'll be looking for predictions on D4.

Please let me know if the PR captures this successfully.

Thanks!
Casey
